# -*- coding: utf-8 -*-
"""Automate_Raden-Fitzal-Bintang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbwEfqmunEOSuYpcYFdNkzMm5j7v1xgN
"""

import pandas as pd
import numpy as np
import kagglehub
import os

from sklearn.preprocessing import StandardScaler, LabelEncoder

# 1. Load Dataset
def load_data():
    path = kagglehub.dataset_download("jessemostipak/hotel-booking-demand")
    csv_path = os.path.join(path, "hotel_bookings.csv")
    df = pd.read_csv(csv_path)
    return df


# 2. Preprocessing Data
def preprocess_data(df):
    # Handling missing values
    df["children"] = df["children"].fillna(0)
    df["country"] = df["country"].fillna("Unknown")
    df["agent"] = df["agent"].fillna(0)
    df["company"] = df["company"].fillna(0)

    # Drop duplicate rows
    df = df.drop_duplicates()

    # Encoding categorical features
    categorical_cols = df.select_dtypes(include="object").columns
    encoder = LabelEncoder()
    for col in categorical_cols:
        df[col] = encoder.fit_transform(df[col])

    # Scaling numerical features (exclude target)
    numeric_cols = df.select_dtypes(include=np.number).columns
    numeric_cols = numeric_cols.drop("is_canceled")

    scaler = StandardScaler()
    df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

    return df

# 3. Save Preprocessed Data
def save_data(df, output_dir="hotelbookingdemand_preprocessing"):
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "hotel_bookings_clean.csv")
    df.to_csv(output_path, index=False)
    print(f"Dataset preprocessing berhasil disimpan di: {output_path}")


# 4. Main Function
def main():
    print("Memulai proses preprocessing...")

    df = load_data()
    print("Dataset berhasil dimuat")

    df_clean = preprocess_data(df)
    print("Preprocessing selesai")

    save_data(df_clean)

    print("Proses preprocessing selesai sepenuhnya")


if __name__ == "__main__":
    main()